version: "2.2"
pipelines:
  - id: postgres-to-kafka
    status: stopped
    description: Postgres to Kafka (CDC)
    connectors:
      - id: postgres-source
        type: source
        plugin: builtin:postgres
        settings:
          tables: "employees"
          url: "postgresql://meroxauser:meroxapass@benchi-postgres:5432/meroxadb"
          cdcMode: "logrepl"
          logrepl.slotName: "conduit_slot"
          logrepl.publicationName: "conduit_pub"
          logrepl.autoCleanup: "true"
          logrepl.withAvroSchema: "false"
          snapshotMode: "never"
          sdk.batch.size: 10000
          sdk.batch.delay: "0s"
          sdk.schema.extract.key.enabled: false
          sdk.schema.extract.payload.enabled: false
      - id: kafka-destination
        type: destination
        plugin: builtin:kafka
        name: kafka-destination
        settings:
          servers: "benchi-kafka:9092"
          topic: "postgres.public.employees"
          compression: "snappy"
          batchBytes: "1000000"
          acks: "one"
          sdk.batch.size: 10000
          sdk.batch.delay: "500ms"
          sdk.record.format: "opencdc/json"
