services:
  benchi-conduit:
    volumes:
      # mount path is relative to the location of the original docker-compose file (/shared/conduit/compose.yml)
      - ../../benchmarks/generator-kafka/conduit/pipeline-structured.yml:/app/pipelines/pipeline.yml
      - ../../benchmarks/generator-kafka/conduit/data:/benchi/data
    environment:
      PAYLOAD_PATH: /benchi/data/payload_postgres_record.txt
