version: "2.2"
pipelines:
  - id: generator-kafka
    status: running
    connectors:
    - id: generator
      type: source
      plugin: builtin:generator
      settings:
        format.type: file # take payload from file, to skip generation overhead
        format.options.path: ${PAYLOAD_PATH} # different payload sizes - 25B, 1kB, 10kB
        # recordCount: 100
        # rate: 1
        sdk.batch.size: 5000
        sdk.batch.delay: 0s
        sdk.schema.extract.key.enabled: false
        sdk.schema.extract.payload.enabled: false
    - id: kafka-destination
      type: destination
      plugin: builtin:kafka
      name: kafka-destination
      settings:
        servers: "benchi-kafka:9092"
        topic: "generator.to.kafka"
        compression: "none"

