version: "2.2"
pipelines:
  - id: generator-kafka
    status: running
    connectors:
      - id: generator
        type: source
        plugin: builtin:generator
        settings:
          collections.users.format.type: structured
          collections.users.format.options.id: int
          collections.users.format.options.name: string
          collections.users.format.options.email: string
          collections.users.format.options.position: string
          collections.users.format.options.salary: int
          collections.users.format.options.full_time: bool
          collections.users.format.options.hire_date: time
          collections.users.format.options.created_at: time
          collections.users.format.options.updated_at: time
          sdk.schema.extract.key.enabled: false
          sdk.schema.extract.payload.enabled: false
      - id: kafka-destination
        type: destination
        plugin: builtin:kafka
        name: kafka-destination
        settings:
          servers: "benchi-kafka:9092"
          topic: "generator.to.kafka"
          compression: "none"

