services:
  benchi-conduit:
    volumes:
      # mount path is relative to the location of the original docker-compose file (/shared/conduit/compose.yml)
      - ../../benchmarks/kafka-snowflake-cdc/conduit/pipeline.yml:/app/pipelines/pipeline.yml
    env_file: ../../benchmarks/kafka-snowflake-cdc/conduit/.env