services:
  benchi-kafka-connect:
    volumes:
      # mount path is relative to the location of the original docker-compose file (/shared/kafka-connect/compose.yml)
      - ../../benchmarks/postgres-kafka-snapshot/kafka-connect/data:/benchi/data
      - ../../benchmarks/postgres-kafka-snapshot/kafka-connect/init:/benchi/init
