services:
  benchi-conduit:
    volumes:
      # mount path is relative to the location of the original docker-compose file (/shared/conduit/compose.yml)
      - ../../benchmarks/generator-chaos/conduit/pipeline-structured.yml:/app/pipelines/pipeline.yml
      - ../../benchmarks/generator-chaos/conduit/data:/benchi/data
