services:
  benchi-conduit:
    container_name: benchi-conduit
    networks:
      - benchi

    image: benchi/conduit
    build: ./benchmark-conduit
    pull_policy: never
    ports:
      - '8080:8080'
    environment:
      CONDUIT_LOG_FORMAT: json
    volumes:
      - ./scripts:/benchi/scripts

networks:
  benchi:
    external: true
