version: "2.2"
pipelines:
    - id: mongo-to-kafka
      status: stopped
      description: MongoDB to Kafka
      connectors:
        - id: mongo-source
          type: source
          plugin: builtin:mongo
          settings:
            collection: users
            db: test
            uri: "mongodb://benchi-mongo1:30001,benchi-mongo2:30002,benchi-mongo3:30003/test?replicaSet=test-replica-set"
            sdk.batch.size: 10000
            sdk.batch.delay: "1s"
            sdk.schema.extract.key.enabled: false
            sdk.schema.extract.payload.enabled: false
        - id: kafka-destination
          type: destination
          plugin: builtin:kafka
          name: kafka-destination
          settings:
            servers: "benchi-kafka:9092"
            topic: mongo.test.users
            compression: "none"
