services:
  benchi-kafka-connect:
    environment:
      BENCHI_CONNECT_COMPONENTS: 'mongodb/kafka-connect-mongodb:1.5.0'
    volumes:
      # mount path is relative to the location of the original docker-compose file (/shared/kafka-connect/compose.yml)
      - ../../benchmarks/mongo-kafka-cdc/kafka-connect/data:/benchi/data
